import os


INDEXER_URL = os.getenv("INDEXER_URL", "http://host.docker.internal:8080")
HEARTBEAT_INTERVAL_SECONDS = int(os.getenv("SSE_HEARTBEAT_SECONDS", "15"))
HASURA_ADMIN_SECRET = os.getenv("HASURA_GRAPHQL_ADMIN_SECRET")
DEFAULT_CHART_WINDOW_SEC = int(os.getenv("CHART_DEFAULT_WINDOW_SEC", "86400"))
DEFAULT_CHART_INTERVAL_SEC = int(os.getenv("CHART_DEFAULT_INTERVAL_SEC", "300"))
COINMK_API_KEY = os.getenv("COINMK_API_KEY")
COINMK_API_ENDPOINT = os.getenv("COINMK_API_ENDPOINT")
COINMK_SYMBOL = os.getenv("COINMK_SYMBOL", "FUEL")
COINMK_POLL_SECONDS = int(os.getenv("COINMK_POLL_SECONDS", "20"))
