/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.102.0
  Forc version: 0.70.1
  Fuel-Core version: 0.46.0
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
  StrSlice,
} from 'fuels';

import type { Option, Enum, Vec } from "./common";

export enum CampaignStatusInput { Active = 'Active', Launched = 'Launched', Denied = 'Denied', Migrated = 'Migrated' };
export enum CampaignStatusOutput { Active = 'Active', Launched = 'Launched', Denied = 'Denied', Migrated = 'Migrated' };
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export type MetadataInput = Enum<{ B256: string, Bytes: Bytes, Int: BigNumberish, String: StdString }>;
export type MetadataOutput = Enum<{ B256: string, Bytes: Bytes, Int: BN, String: StdString }>;
export type StateInput = Enum<{ Uninitialized: undefined, Initialized: IdentityInput, Revoked: undefined }>;
export type StateOutput = Enum<{ Uninitialized: void, Initialized: IdentityOutput, Revoked: void }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type BondingCurveInput = { sold_supply: BigNumberish, max_supply: BigNumberish, base_price: BigNumberish, slope: BigNumberish };
export type BondingCurveOutput = { sold_supply: BN, max_supply: BN, base_price: BN, slope: BN };
export type BurnEventInput = { asset_id: AssetIdInput, sender: IdentityInput, amount: BigNumberish };
export type BurnEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput, amount: BN };
export type BuyEventInput = { asset_id: AssetIdInput, sender: IdentityInput, amount: BigNumberish, cost: BigNumberish, sold_supply: BigNumberish };
export type BuyEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput, amount: BN, cost: BN, sold_supply: BN };
export type CampaignInput = { target: BigNumberish, creator: IdentityInput, status: CampaignStatusInput, token_id: AssetIdInput, sub_id: string, total_pledged: BigNumberish, total_supply: BigNumberish, curve: BondingCurveInput, amm_reserved: BigNumberish };
export type CampaignOutput = { target: BN, creator: IdentityOutput, status: CampaignStatusOutput, token_id: AssetIdOutput, sub_id: string, total_pledged: BN, total_supply: BN, curve: BondingCurveOutput, amm_reserved: BN };
export type CampaignCreatedEventInput = { asset_id: AssetIdInput, creator: IdentityInput, sub_id: string, target: BigNumberish, token_info: TokenInfoInput };
export type CampaignCreatedEventOutput = { asset_id: AssetIdOutput, creator: IdentityOutput, sub_id: string, target: BN, token_info: TokenInfoOutput };
export type CampaignDeniedEventInput = { asset_id: AssetIdInput, sender: IdentityInput };
export type CampaignDeniedEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput };
export type CampaignLaunchedEventInput = { asset_id: AssetIdInput, sender: IdentityInput, users_share: BigNumberish, remaining_supply: BigNumberish, amm_supply: BigNumberish, base_price: BigNumberish, slope: BigNumberish, max_supply: BigNumberish };
export type CampaignLaunchedEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput, users_share: BN, remaining_supply: BN, amm_supply: BN, base_price: BN, slope: BN, max_supply: BN };
export type ClaimEventInput = { asset_id: AssetIdInput, sender: IdentityInput, amount: BigNumberish };
export type ClaimEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput, amount: BN };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type MintEventInput = { asset_id: AssetIdInput, recipient: IdentityInput, amount: BigNumberish };
export type MintEventOutput = { asset_id: AssetIdOutput, recipient: IdentityOutput, amount: BN };
export type PledgedEventInput = { asset_id: AssetIdInput, sender: IdentityInput, amount: BigNumberish, total_pledged: BigNumberish };
export type PledgedEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput, amount: BN, total_pledged: BN };
export type SellEventInput = { asset_id: AssetIdInput, sender: IdentityInput, amount: BigNumberish, payout: BigNumberish, sold_supply: BigNumberish };
export type SellEventOutput = { asset_id: AssetIdOutput, sender: IdentityOutput, amount: BN, payout: BN, sold_supply: BN };
export type TokenInfoInput = { asset_id: AssetIdInput, name: StdString, ticker: StdString, description: StdString, decimals: BigNumberish, image: StdString };
export type TokenInfoOutput = { asset_id: AssetIdOutput, name: StdString, ticker: StdString, description: StdString, decimals: number, image: StdString };
export type TotalSupplyEventInput = { asset: AssetIdInput, supply: BigNumberish, sender: IdentityInput };
export type TotalSupplyEventOutput = { asset: AssetIdOutput, supply: BN, sender: IdentityOutput };

export type LaunchpadConfigurables = Partial<{
  DEFAULT_DECIMALS: BigNumberish;
  MIGRATION_TARGET: BigNumberish;
  INITIAL_SUPPLY: BigNumberish;
  PLEDGE_ASSET_ID: string;
  CURVE_SUPPLY_PERCENT: BigNumberish;
  INSTANT_LAUNCH_THRESHOLD_PERCENT: BigNumberish;
}>;

const abi = {
  "programType": "contract",
  "specVersion": "1.2",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum src5::State",
      "concreteTypeId": "287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca",
      "metadataTypeId": 0
    },
    {
      "type": "enum src7::Metadata",
      "concreteTypeId": "a7c295c5428e2fe8ba421f1fcb648719961287a4c814f1f1c64e0eeebf14adcb",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 2
    },
    {
      "type": "enum std::option::Option<b256>",
      "concreteTypeId": "0c2beb9013490c4f753f2757dfe2d8340b22ce3827d596d81d249b7038033cb6",
      "metadataTypeId": 3,
      "typeArguments": [
        "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
      ]
    },
    {
      "type": "enum std::option::Option<enum src7::Metadata>",
      "concreteTypeId": "f75762acece1fcc7aa89ff02eb493a46c576a3a9ccfcfc3cea2d3ce711e5bc86",
      "metadataTypeId": 3,
      "typeArguments": [
        "a7c295c5428e2fe8ba421f1fcb648719961287a4c814f1f1c64e0eeebf14adcb"
      ]
    },
    {
      "type": "enum std::option::Option<struct std::string::String>",
      "concreteTypeId": "7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0",
      "metadataTypeId": 3,
      "typeArguments": [
        "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
      ]
    },
    {
      "type": "enum std::option::Option<u64>",
      "concreteTypeId": "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
      "metadataTypeId": 3,
      "typeArguments": [
        "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
      ]
    },
    {
      "type": "enum std::option::Option<u8>",
      "concreteTypeId": "2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1",
      "metadataTypeId": 3,
      "typeArguments": [
        "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
      ]
    },
    {
      "type": "str",
      "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
    },
    {
      "type": "struct events::BurnEvent",
      "concreteTypeId": "af82480fdd08f1950b75df893648ba1dbee413c616d09755dd8497b582debf45",
      "metadataTypeId": 7
    },
    {
      "type": "struct events::BuyEvent",
      "concreteTypeId": "e5d3acecd2b71db2d42a1508d1d48ac751330f307d256d8894db211c23c2815a",
      "metadataTypeId": 8
    },
    {
      "type": "struct events::CampaignCreatedEvent",
      "concreteTypeId": "196902c92896561f95e35839c11957d4cb69848d385eeaa86515cbe22afbb812",
      "metadataTypeId": 9
    },
    {
      "type": "struct events::CampaignDeniedEvent",
      "concreteTypeId": "b42351897d1274ab71a60107e31cb47598682fd90b67ebbe30621865d682e663",
      "metadataTypeId": 10
    },
    {
      "type": "struct events::CampaignLaunchedEvent",
      "concreteTypeId": "c29fbe9ca18df251d732cb4f8397ab2231c817747dff2afc2a358bbc32e58f58",
      "metadataTypeId": 11
    },
    {
      "type": "struct events::ClaimEvent",
      "concreteTypeId": "1fa0c6da5fd6fd691795bd27aadcc15cdc0280686eab924a3884591d8d82eeab",
      "metadataTypeId": 12
    },
    {
      "type": "struct events::MintEvent",
      "concreteTypeId": "8cfe38d1ba0d97380df81da6075bed5def90f5bde5e54647772963da050fde12",
      "metadataTypeId": 13
    },
    {
      "type": "struct events::PledgedEvent",
      "concreteTypeId": "efc3ff2962ac53b0d658fef7024d9b9df649f77a5e512c743f6451d648f60ab9",
      "metadataTypeId": 14
    },
    {
      "type": "struct events::SellEvent",
      "concreteTypeId": "78df0c9c7f494f8f480f4abfe69400be9d2bcefc0bcf14dcb1db1cae9c6e39b2",
      "metadataTypeId": 15
    },
    {
      "type": "struct src20::TotalSupplyEvent",
      "concreteTypeId": "7a3907033239b7e20b602aaf2a1a55863934467688426a359aae8b410786d2ba",
      "metadataTypeId": 16
    },
    {
      "type": "struct std::asset_id::AssetId",
      "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
      "metadataTypeId": 18
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 22
    },
    {
      "type": "struct std::vec::Vec<struct types::campaign::Campaign>",
      "concreteTypeId": "1ec264705714a469ba386512879d87a6060a454b1b43d1d9228a7bfb38020abf",
      "metadataTypeId": 24,
      "typeArguments": [
        "25508f36b510e4caaa34f13132d8c5890fee213dfdc93c792b52274402720f89"
      ]
    },
    {
      "type": "struct std::vec::Vec<struct types::structs::TokenInfo>",
      "concreteTypeId": "cea4b27422ef9bec713c723d02ee6ed5be55227cbfb2561b416abde46eb1eac6",
      "metadataTypeId": 24,
      "typeArguments": [
        "83db1f185e1891658bd68a188647e181b3e4191463f62ff09c2c8fec8767b88d"
      ]
    },
    {
      "type": "struct types::campaign::Campaign",
      "concreteTypeId": "25508f36b510e4caaa34f13132d8c5890fee213dfdc93c792b52274402720f89",
      "metadataTypeId": 26
    },
    {
      "type": "struct types::structs::TokenInfo",
      "concreteTypeId": "83db1f185e1891658bd68a188647e181b3e4191463f62ff09c2c8fec8767b88d",
      "metadataTypeId": 27
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    },
    {
      "type": "u8",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
    }
  ],
  "metadataTypes": [
    {
      "type": "enum src5::State",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "Uninitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Initialized",
          "typeId": 2
        },
        {
          "name": "Revoked",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum src7::Metadata",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "B256",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "Bytes",
          "typeId": 19
        },
        {
          "name": "Int",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "String",
          "typeId": 22
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Address",
          "typeId": 17
        },
        {
          "name": "ContractId",
          "typeId": 21
        }
      ]
    },
    {
      "type": "enum std::option::Option",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "None",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Some",
          "typeId": 5
        }
      ],
      "typeParameters": [
        5
      ]
    },
    {
      "type": "enum types::campaign::CampaignStatus",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "Active",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Launched",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Denied",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Migrated",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 5
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 6
    },
    {
      "type": "struct events::BurnEvent",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct events::BuyEvent",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "cost",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "sold_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct events::CampaignCreatedEvent",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "creator",
          "typeId": 2
        },
        {
          "name": "sub_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "target",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "token_info",
          "typeId": 27
        }
      ]
    },
    {
      "type": "struct events::CampaignDeniedEvent",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        }
      ]
    },
    {
      "type": "struct events::CampaignLaunchedEvent",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        },
        {
          "name": "users_share",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "remaining_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "amm_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "base_price",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "slope",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "max_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct events::ClaimEvent",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct events::MintEvent",
      "metadataTypeId": 13,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "recipient",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct events::PledgedEvent",
      "metadataTypeId": 14,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "total_pledged",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct events::SellEvent",
      "metadataTypeId": 15,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "sender",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "payout",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "sold_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct src20::TotalSupplyEvent",
      "metadataTypeId": 16,
      "components": [
        {
          "name": "asset",
          "typeId": 18
        },
        {
          "name": "supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "sender",
          "typeId": 2
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 17,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::asset_id::AssetId",
      "metadataTypeId": 18,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 19,
      "components": [
        {
          "name": "buf",
          "typeId": 20
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 20,
      "components": [
        {
          "name": "ptr",
          "typeId": 6
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 21,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 22,
      "components": [
        {
          "name": "bytes",
          "typeId": 19
        }
      ]
    },
    {
      "type": "struct std::vec::RawVec",
      "metadataTypeId": 23,
      "components": [
        {
          "name": "ptr",
          "typeId": 6
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        5
      ]
    },
    {
      "type": "struct std::vec::Vec",
      "metadataTypeId": 24,
      "components": [
        {
          "name": "buf",
          "typeId": 23,
          "typeArguments": [
            {
              "name": "",
              "typeId": 5
            }
          ]
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        5
      ]
    },
    {
      "type": "struct types::bonding::BondingCurve",
      "metadataTypeId": 25,
      "components": [
        {
          "name": "sold_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "max_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "base_price",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "slope",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct types::campaign::Campaign",
      "metadataTypeId": 26,
      "components": [
        {
          "name": "target",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "creator",
          "typeId": 2
        },
        {
          "name": "status",
          "typeId": 4
        },
        {
          "name": "token_id",
          "typeId": 18
        },
        {
          "name": "sub_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "total_pledged",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "total_supply",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "curve",
          "typeId": 25
        },
        {
          "name": "amm_reserved",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct types::structs::TokenInfo",
      "metadataTypeId": 27,
      "components": [
        {
          "name": "asset_id",
          "typeId": 18
        },
        {
          "name": "name",
          "typeId": 22
        },
        {
          "name": "ticker",
          "typeId": 22
        },
        {
          "name": "description",
          "typeId": 22
        },
        {
          "name": "decimals",
          "typeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        },
        {
          "name": "image",
          "typeId": 22
        }
      ]
    }
  ],
  "functions": [
    {
      "name": "owner",
      "inputs": [],
      "output": "287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "decimals",
      "inputs": [
        {
          "name": "asset",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "name",
      "inputs": [
        {
          "name": "asset",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "symbol",
      "inputs": [
        {
          "name": "asset",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "total_assets",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "total_supply",
      "inputs": [
        {
          "name": "asset",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "metadata",
      "inputs": [
        {
          "name": "asset",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        },
        {
          "name": "key",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        }
      ],
      "output": "f75762acece1fcc7aa89ff02eb493a46c576a3a9ccfcfc3cea2d3ce711e5bc86",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "buy",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Buys tokens from bonding curve using the sent base-asset budget."
          ]
        }
      ]
    },
    {
      "name": "claim",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Claims user allocation after launch."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " User can claim only once; returns false if no pledge found."
          ]
        }
      ]
    },
    {
      "name": "create_campaign",
      "inputs": [
        {
          "name": "name",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "ticker",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "description",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "image",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        }
      ],
      "output": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Creates a new campaign and initializes its metadata."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Generates deterministic sub_id from (counter, sender)."
          ]
        }
      ]
    },
    {
      "name": "deny_campaign",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Denies an active campaign and refunds all pledges."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Only valid for Active campaigns."
          ]
        }
      ]
    },
    {
      "name": "get_assets",
      "inputs": [],
      "output": "cea4b27422ef9bec713c723d02ee6ed5be55227cbfb2561b416abde46eb1eac6",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns metadata for all created assets."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Iterates storage.assets and resolves TokenInfo for each asset id."
          ]
        }
      ]
    },
    {
      "name": "get_campaign",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "25508f36b510e4caaa34f13132d8c5890fee213dfdc93c792b52274402720f89",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns campaign by asset id (reverts if not found)."
          ]
        }
      ]
    },
    {
      "name": "get_campaign_counter",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns total number of campaigns created."
          ]
        }
      ]
    },
    {
      "name": "get_campaigns",
      "inputs": [],
      "output": "1ec264705714a469ba386512879d87a6060a454b1b43d1d9228a7bfb38020abf",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns all stored campaigns."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Iterates storage.assets and collects Campaigns that exist."
          ]
        }
      ]
    },
    {
      "name": "get_pledge",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        },
        {
          "name": "sender",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns pledged amount for a user and campaign."
          ]
        }
      ]
    },
    {
      "name": "get_token_info",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "83db1f185e1891658bd68a188647e181b3e4191463f62ff09c2c8fec8767b88d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns token info for asset id."
          ]
        }
      ]
    },
    {
      "name": "get_total_pledged",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns total pledged amount for a campaign."
          ]
        }
      ]
    },
    {
      "name": "initialize",
      "inputs": [
        {
          "name": "owner",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "launch_campaign",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Launches a campaign: initializes curve, mints full supply to contract."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Owner-only; campaign must be active and have pledges."
          ]
        }
      ]
    },
    {
      "name": "pledge",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Pledges base asset to an active campaign."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Enforces max pledge per user and exact msg_amount."
          ]
        }
      ]
    },
    {
      "name": "refund_pledge",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Refunds user pledge after campaign denial."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " User can refund only once; returns false if no pledge found."
          ]
        }
      ]
    },
    {
      "name": "sell",
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "min_payout",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Sells tokens back to bonding curve."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Caller must send token amount; returns payout in base asset."
          ]
        }
      ]
    },
    {
      "name": "set_owner",
      "inputs": [
        {
          "name": "owner",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "burn",
      "inputs": [
        {
          "name": "sub_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "name": "mint",
      "inputs": [
        {
          "name": "recipient",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "sub_id",
          "concreteTypeId": "0c2beb9013490c4f753f2757dfe2d8340b22ce3827d596d81d249b7038033cb6"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "10098701174489624218",
      "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
    },
    {
      "logId": "16560770387918921138",
      "concreteTypeId": "e5d3acecd2b71db2d42a1508d1d48ac751330f307d256d8894db211c23c2815a"
    },
    {
      "logId": "2279040052662566249",
      "concreteTypeId": "1fa0c6da5fd6fd691795bd27aadcc15cdc0280686eab924a3884591d8d82eeab"
    },
    {
      "logId": "1830997786495440415",
      "concreteTypeId": "196902c92896561f95e35839c11957d4cb69848d385eeaa86515cbe22afbb812"
    },
    {
      "logId": "12980308201962632363",
      "concreteTypeId": "b42351897d1274ab71a60107e31cb47598682fd90b67ebbe30621865d682e663"
    },
    {
      "logId": "14024137344589623889",
      "concreteTypeId": "c29fbe9ca18df251d732cb4f8397ab2231c817747dff2afc2a358bbc32e58f58"
    },
    {
      "logId": "17276933148737557424",
      "concreteTypeId": "efc3ff2962ac53b0d658fef7024d9b9df649f77a5e512c743f6451d648f60ab9"
    },
    {
      "logId": "8709694070647771023",
      "concreteTypeId": "78df0c9c7f494f8f480f4abfe69400be9d2bcefc0bcf14dcb1db1cae9c6e39b2"
    },
    {
      "logId": "8807078256608655330",
      "concreteTypeId": "7a3907033239b7e20b602aaf2a1a55863934467688426a359aae8b410786d2ba"
    },
    {
      "logId": "12646749936579834261",
      "concreteTypeId": "af82480fdd08f1950b75df893648ba1dbee413c616d09755dd8497b582debf45"
    },
    {
      "logId": "10159620282815190840",
      "concreteTypeId": "8cfe38d1ba0d97380df81da6075bed5def90f5bde5e54647772963da050fde12"
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "DEFAULT_DECIMALS",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b",
      "offset": 82240,
      "indirect": false
    },
    {
      "name": "MIGRATION_TARGET",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 82264,
      "indirect": false
    },
    {
      "name": "INITIAL_SUPPLY",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 82248,
      "indirect": false
    },
    {
      "name": "PLEDGE_ASSET_ID",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "offset": 82272,
      "indirect": false
    },
    {
      "name": "CURVE_SUPPLY_PERCENT",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 82232,
      "indirect": false
    },
    {
      "name": "INSTANT_LAUNCH_THRESHOLD_PERCENT",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 82256,
      "indirect": false
    }
  ],
  "errorCodes": {},
  "panickingCalls": {}
};

const storageSlots: StorageSlot[] = [
  {
    "key": "6189f6fb2b7278c2a5f1b1ebfc35d4838d6c414acd1f700a7cf63bfc75e71a2b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "6189f6fb2b7278c2a5f1b1ebfc35d4838d6c414acd1f700a7cf63bfc75e71a2c",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "90d46f53814b9122ab29ebd089019d58a19453fca9a53103ae4bd375715dc67e",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class LaunchpadInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    owner: FunctionFragment;
    decimals: FunctionFragment;
    name: FunctionFragment;
    symbol: FunctionFragment;
    total_assets: FunctionFragment;
    total_supply: FunctionFragment;
    metadata: FunctionFragment;
    buy: FunctionFragment;
    claim: FunctionFragment;
    create_campaign: FunctionFragment;
    deny_campaign: FunctionFragment;
    get_assets: FunctionFragment;
    get_campaign: FunctionFragment;
    get_campaign_counter: FunctionFragment;
    get_campaigns: FunctionFragment;
    get_pledge: FunctionFragment;
    get_token_info: FunctionFragment;
    get_total_pledged: FunctionFragment;
    initialize: FunctionFragment;
    launch_campaign: FunctionFragment;
    pledge: FunctionFragment;
    refund_pledge: FunctionFragment;
    sell: FunctionFragment;
    set_owner: FunctionFragment;
    burn: FunctionFragment;
    mint: FunctionFragment;
  };
}

export class Launchpad extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: LaunchpadInterface;
  declare functions: {
    owner: InvokeFunction<[], StateOutput>;
    decimals: InvokeFunction<[asset: AssetIdInput], Option<number>>;
    name: InvokeFunction<[asset: AssetIdInput], Option<StdString>>;
    symbol: InvokeFunction<[asset: AssetIdInput], Option<StdString>>;
    total_assets: InvokeFunction<[], BN>;
    total_supply: InvokeFunction<[asset: AssetIdInput], Option<BN>>;
    metadata: InvokeFunction<[asset: AssetIdInput, key: StdString], Option<MetadataOutput>>;
    buy: InvokeFunction<[asset_id: AssetIdInput], BN>;
    claim: InvokeFunction<[asset_id: AssetIdInput], boolean>;
    create_campaign: InvokeFunction<[name: StdString, ticker: StdString, description: StdString, image: StdString], AssetIdOutput>;
    deny_campaign: InvokeFunction<[asset_id: AssetIdInput], boolean>;
    get_assets: InvokeFunction<[], Vec<TokenInfoOutput>>;
    get_campaign: InvokeFunction<[asset_id: AssetIdInput], CampaignOutput>;
    get_campaign_counter: InvokeFunction<[], BN>;
    get_campaigns: InvokeFunction<[], Vec<CampaignOutput>>;
    get_pledge: InvokeFunction<[asset_id: AssetIdInput, sender: IdentityInput], BN>;
    get_token_info: InvokeFunction<[asset_id: AssetIdInput], TokenInfoOutput>;
    get_total_pledged: InvokeFunction<[asset_id: AssetIdInput], BN>;
    initialize: InvokeFunction<[owner: IdentityInput], void>;
    launch_campaign: InvokeFunction<[asset_id: AssetIdInput], boolean>;
    pledge: InvokeFunction<[asset_id: AssetIdInput, amount: BigNumberish], boolean>;
    refund_pledge: InvokeFunction<[asset_id: AssetIdInput], boolean>;
    sell: InvokeFunction<[asset_id: AssetIdInput, amount: BigNumberish, min_payout: BigNumberish], BN>;
    set_owner: InvokeFunction<[owner: IdentityInput], void>;
    burn: InvokeFunction<[sub_id: string, amount: BigNumberish], void>;
    mint: InvokeFunction<[recipient: IdentityInput, sub_id: Option<string>, amount: BigNumberish], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
